package server

// The gateway's URL surface, kept apart from server construction so adding an
// endpoint and changing how the server is built stay separate edits.

func (s *Server) routes() {
	s.mux.HandleFunc("/livez", s.handleLive)
	s.mux.HandleFunc("/readyz", s.handleHealth)
	s.mux.HandleFunc("/healthz", s.handleHealth)
	s.mux.HandleFunc("/metrics", s.handleMetrics)
	s.registerModelRoutes()
	// The in-flight gauge covers exactly the endpoints that route to an upstream, so
	// it stays comparable with requests_total. Catalog lookups and count_tokens are
	// local and never produce a request count, and admin traffic and scrapes are not
	// gateway load at all.
	s.mux.HandleFunc("/v1/chat/completions", s.gatewayInFlight(s.handleChatCompletions))
	s.mux.HandleFunc("/v1/messages", s.gatewayInFlight(s.handleAnthropicMessages))
	s.mux.HandleFunc("/v1/messages/count_tokens", s.handleAnthropicCountTokens)
	s.mux.HandleFunc("/v1/responses", s.gatewayInFlight(s.handleResponses))
	s.mux.HandleFunc("/v1/responses/compact", s.gatewayInFlight(s.handleResponsesCompact))
	s.mux.HandleFunc("/v1/embeddings", s.gatewayInFlight(s.handleEmbeddings))
	s.mux.HandleFunc("/v1/images/generations", s.handleImageGenerations)
	s.mux.HandleFunc("/v1/images/edits", s.handleImageEdits)
	s.mux.HandleFunc("/v1/image-jobs/", s.handleImageJob)
	s.mux.HandleFunc("/v1/image-assets/", s.handleImageAsset)
	s.registerGatewayRoutes()
	s.mux.HandleFunc("/api/v1/analytics/token-costs", s.handleTokenCostAnalytics)

	s.mux.HandleFunc("/api/admin/auth/login", s.handleAdminLogin)
	s.mux.HandleFunc("/api/admin/auth/logout", s.handleAdminLogout)
	s.mux.HandleFunc("/api/admin/auth/me", s.handleAdminMe)
	s.mux.HandleFunc("/api/admin/auth/reset-password", s.handleAdminResetPassword)
	s.mux.HandleFunc("/api/admin/auth/identity-providers", s.handleAdminAuthIdentityProviders)
	s.mux.HandleFunc("/api/admin/auth/oauth/start", s.handleAdminOAuthStart)
	s.mux.HandleFunc("/api/admin/auth/oauth/callback", s.handleAdminOAuthCallback)
	s.mux.HandleFunc("/api/admin/overview", s.handleAdminOverview)
	s.mux.HandleFunc("/api/admin/playground/chat", s.handleAdminPlaygroundChat)
	s.mux.HandleFunc("/api/admin/playground/chat/stream", s.handleAdminPlaygroundChatStream)
	s.mux.HandleFunc("/api/admin/projects", s.handleAdminProjects)
	s.mux.HandleFunc("/api/admin/projects/", s.handleAdminProjectNested)
	s.mux.HandleFunc("/api/admin/users", s.handleAdminUsers)
	s.mux.HandleFunc("/api/admin/users/import", s.handleAdminUsersImport)
	s.mux.HandleFunc("/api/admin/users/", s.handleAdminUserItem)
	s.mux.HandleFunc("/api/admin/provider-catalog", s.handleAdminProviderCatalog)
	s.mux.HandleFunc("/api/admin/provider-catalog/", s.handleAdminProviderCatalogItem)
	s.mux.HandleFunc("/api/admin/provider-adapters", s.handleAdminProviderAdapters)
	s.mux.HandleFunc("/api/admin/provider-account-oauth/openai/generate-auth-url", s.handleAdminOpenAIAccountOAuthGenerateAuthURL)
	s.mux.HandleFunc("/api/admin/provider-account-oauth/openai/exchange-code", s.handleAdminOpenAIAccountOAuthExchangeCode)
	s.mux.HandleFunc("/api/admin/provider-account-oauth/openai/oauth/callback", s.handleOpenAIAccountOAuthCallback)
	s.mux.HandleFunc("/api/admin/api-keys", s.handleAdminAPIKeys)
	s.mux.HandleFunc("/api/admin/api-keys/", s.handleAdminAPIKeyItem)
	s.mux.HandleFunc("/api/admin/analytics/credentials", s.handleAdminAnalyticsCredentials)
	s.mux.HandleFunc("/api/admin/analytics/credentials/", s.handleAdminAnalyticsCredentialItem)
	s.mux.HandleFunc("/api/admin/providers", s.handleAdminProviders)
	s.mux.HandleFunc("/api/admin/providers/monitoring", s.handleAdminProviderMonitoring)
	s.mux.HandleFunc("/api/admin/providers/", s.handleAdminProviderNested)
	s.mux.HandleFunc("/api/admin/provider-resources", s.handleAdminProviderResources)
	s.mux.HandleFunc("/api/admin/provider-resources/", s.handleAdminProviderResourceNested)
	s.mux.HandleFunc("/api/admin/provider-models/import", s.handleAdminProviderModelImport)
	s.mux.HandleFunc("/api/admin/provider-models", s.handleAdminProviderModels)
	s.mux.HandleFunc("/api/admin/provider-models/", s.handleAdminProviderModelItem)
	s.mux.HandleFunc("/api/admin/models", s.handleAdminModels)
	s.mux.HandleFunc("/api/admin/models/restore-defaults", s.handleAdminModelsRestoreDefaults)
	s.mux.HandleFunc("/api/admin/models/", s.handleAdminModelItem)
	s.mux.HandleFunc("/api/admin/model-routing-policies/", s.handleAdminModelRoutingPolicy)
	s.mux.HandleFunc("/api/admin/routing-policies/simulate", s.handleAdminRoutingPolicySimulation)
	s.mux.HandleFunc("/api/admin/routing-policies/", s.handleAdminRoutingPolicyAction)
	s.mux.HandleFunc("/api/admin/routing-rules", s.handleAdminRoutes)
	s.mux.HandleFunc("/api/admin/routing-rules/", s.handleAdminRouteItem)
	s.mux.HandleFunc("/api/admin/resources/", s.handleAdminResources)
	s.mux.HandleFunc("/api/admin/sqlite/backups", s.handleAdminSQLiteBackups)
	s.mux.HandleFunc("/api/admin/sqlite/backups/", s.handleAdminSQLiteBackupItem)
	s.mux.HandleFunc("/api/admin/billing/generate", s.handleAdminGenerateBilling)
	s.registerBillingRoutes()
	s.mux.HandleFunc("/api/admin/export/", s.handleAdminExport)
	s.mux.HandleFunc("/api/admin/usage/summary", s.handleAdminUsageSummary)
	s.mux.HandleFunc("/api/admin/usage/breakdown", s.handleAdminUsageBreakdown)
	s.mux.HandleFunc("/api/admin/usage/timeseries", s.handleAdminUsageTimeseries)
	s.mux.HandleFunc("/api/admin/audit/requests", s.handleAdminRequestLogs)
	s.mux.HandleFunc("/api/admin/audit/requests/", s.handleAdminRequestDetail)
	s.mux.HandleFunc("/api/admin/audit/image-jobs", s.handleAdminImageJobs)
	s.mux.HandleFunc("/api/admin/audit/events", s.handleAdminAuditEvents)
	s.mux.HandleFunc("/api/admin/alerts", s.handleAdminAlerts)
	s.mux.HandleFunc("/api/admin/alerts/", s.handleAdminAlertItem)
	s.mux.HandleFunc("/api/admin/alert-deliveries", s.handleAdminAlertDeliveries)
	s.mux.HandleFunc("/api/admin/approvals", s.handleAdminApprovals)
	s.mux.HandleFunc("/api/admin/approvals/", s.handleAdminApprovalItem)
	s.mux.HandleFunc("/api/admin/system/db-status", s.handleAdminSystemDBStatus)
	s.mux.HandleFunc("/api/admin/system/version", s.handleAdminSystemVersion)
	s.mux.HandleFunc("/api/admin/system/update", s.handleAdminSystemUpdate)
	s.mux.HandleFunc("/api/admin/system/rollback", s.handleAdminSystemRollback)
	s.mux.HandleFunc("/api/admin/system/restart", s.handleAdminSystemRestart)
	s.mux.HandleFunc("/api/admin/system/rollback-versions", s.handleAdminRollbackVersions)
}
