import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The docs tree is generated from the repository documentation by
// scripts/sync-docs.mjs; sections and ordering live in that script.
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'link',
      href: '/',
      label: 'Introduction',
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
